// Assignment Code
var generateBtn = document.querySelector("#generate");

// Write password to the #password input
function writePassword() {
  var password = generatePassword();
  var passwordText = document.querySelector("#password");

  passwordText.value = password;

}

// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);

/* pseudocode
1. create prompt1 for password criteria that allows user to choose which criteria to include in the pw
2. create prompt2  for the length of the pw that allows user to choose the length 8=<x=<128
3. create prompt3for character types giving a choice of including lowercase, uppercase, numeric, and/or special characters
[for step 3, better asks user to choose on each seperatly. group it all together is the most ideal way though]
4. check to see if at least one character type is selected
5. if not on step 4, return to the missing question that hasn't been answered
6. if yes (meaning when all prompts are answered), the pw is generated
7. alert that displays the password generated by the system
*/

